### ISSUE TITLE
有动态路由这块的功能吗？

### ISSUE THREAD

**Issue by ZhouYC404** [1esse/vue-clownfish-admin#1]
大佬你好，我是vue3和typescript新手，想问一下这个项目有木有动态路由这块的代码？就是根据后端返回的树形json动态生成左侧路由的这种，类似角色权限控制。

**Comment by 1esse** [comment]
你好，现在示例已经出来了，可以参考示例

**Comment by ZhouYC404** [comment]
> 你好，动态路由需要将json转成路由属性，再推进路由。
> 
> ```
> router.addRoute(newRoute)
> router.options.routes.push(newRoute)
> ```
> 
> 根据vue-router文档提示：
> 
> ```
> 请注意，添加路由并不会触发新的导航。也就是说，除非触发新的导航，否则不会显示所添加的路由。
> ```
> 
> 在添加路由后，你需要触发一次新导航以添加新的路由，可以使用框架提供的redirect.vue页面进行中转。
> 
> ```
> router.replace('/redirect/跳转页.vue') # 路由方式跳转
> next('/redirect/跳转页.vue') # 在permission.ts作权限控制使用此方式
> ```

好的，谢谢~
