### ISSUE TITLE
TS声明文件中为啥不需要export呢？

### ISSUE THREAD

**Issue by ZhouYC404** [1esse/vue-clownfish-admin#2]
大佬，再问一个问题，我看代码的时候发现像stores.d.ts，layout.d.ts这些声明文件中定义了一些全局interface，为啥这些声明文件不需要export，然后业务代码里边也不需要import却可以直接使用这些interface呢？

**Comment by 1esse** [comment]
已经被tsconfig.json的include包含进来了

**Comment by ZhouYC404** [comment]
> 已经被tsconfig.json的include包含进来了

好的，再次感谢~
