### ISSUE TITLE
请教为啥我切换路由后页面是空白的？

### ISSUE THREAD

**Issue by ufoozhenghao** [1esse/vue-clownfish-admin#3]
[仓库连接](https://github.com/ufoozhenghao/SHM_Vue3)

路由那块没看懂 顺便请教一下开发的话往那个routes里面写啊？

**Comment by 1esse** [comment]
1. 可能是vite的hmr和vue组件keep-alive冲突了，可以见[https://github.com/vuejs/core/pull/5165](https://github.com/vuejs/core/pull/5165)，开发的时候建议把layout/index.ts中的keep-alive注释掉。
2. route路由放在routes里面，dashboardRoute和constantRoutes是固定的。

**Comment by ufoozhenghao** [comment]
ok 解决了
