### ISSUE TITLE
dev mock没有生效

### ISSUE THREAD

**Issue by humuchen** [1esse/vue-clownfish-admin#5]
1.dev环境起来之后 mock好像没有生效。

**Comment by 1esse** [comment]
检查一下是不是路径错了，默认是开启文件名称拼接的，可在appConfig.ts里面找到mockNamespace关闭。
```
/**
 * mock是否开启namespace，开启后文件名将作为前缀拼接在url
 */
export const mockNamespace: boolean = true
```

**Comment by humuchen** [comment]
靠谱，关闭这个已解决。
/**
 * mock是否开启namespace，开启后文件名将作为前缀拼接在url
 */
export const mockNamespace: boolean = true
